version: 2
updates:
- package-ecosystem: maven
  directory: "/backend"
  schedule:
    interval: daily
    time: "16:00"
  open-pull-requests-limit: 0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "16:00"
  open-pull-requests-limit: 0
