version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/backend"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
#  - package_manager: "javascript"
#    directory: "/electron"
#    update_schedule: "live"
#  - package_manager: "javascript"
#    directory: "/native"
#    update_schedule: "live"
#  - package_manager: "javascript"
#    directory: "/common"
#    update_schedule: "live"
#  - package_manager: "docker"
#    directory: "/frontend"
#    update_schedule: "weekly"
#  - package_manager: "daily"
#    directory: "/electron"
#    update_schedule: "weekly"
#  - package_manager: "daily"
#    directory: "/native"
#    update_schedule: "weekly"
#  - package_manager: "daily"
#    directory: "/common"
#    update_schedule: "weekly"
#  - package_manager: "daily"
#    directory: "/backend"
#    update_schedule: "daily"
